language: python

dist: xenial

python:
  - "3.7"
  - "3.8-dev"

install:
  - pip install codecov
  - pip install pipenv
  - pipenv update --dev --pre

script:
  - pipenv run pytest --verbose --cov

after_success:
  - codecov
