language: python

dist: xenial

python:
  - "3.7"

install:
  - pip install pipenv
  - pipenv update --dev --pre

before_script:
  - pipenv run black --check .

script:
  - pipenv run pytest --verbose --cov

after_success:
  - pipenv run codecov
