language: python

dist: xenial

python:
  - "3.7"

env:
  - PIPENV_VERBOSITY=-1

install:
  - pip install pipenv
  - make deps/install

before_script:
  - make black/check

script:
  - make test

after_success:
  - make codecov
